# Generated by Django 5.2.6 on 2025-10-12 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Throw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('throw_number', models.IntegerField()),
                ('points', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('daily_stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='throws', to='myapp.dailystats')),
            ],
        ),
    ]
