# Generated by Django 5.2.6 on 2025-10-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_throw'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystats',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
